title: Retro Yellow
markdown: kramdown
url: ''
baseurl: ''
color_scheme: yellow
author:
  name: Sharad Raj Singh Maurya
  email: dev_sharad@outlook.com
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
paginate_path: '/page:num/'
paginate: 5
defaults:
  - scope:
      path: ''
    values:
      layout: post
exclude:
  - sitemap.xml
  - feed.xml
  - LICENSE
  - README.md
